### ISSUE TITLE
use this repo as single source of info/code for fireSense?

### ISSUE THREAD

**Issue by achubaty** [ygc2l/fireSense_Tutorial#1]
Hi Jean, thanks for starting a tutorial. I think it'd also be useful to consolidate the various fireSense pieces here in this repo:

1. rename `fireSense_Tutorial` repo to `fireSense`;
2. rename `fireSense_tutorial.Rmd` to `README.Rmd`;
3. delete `README.md`;
4. link the `fireSense_*` modules as git submodules in this repo

**Comment by ygc2l** [comment]
Will do at some point, thanks for the suggestions.
